export const AwesomeIcons = [
  { label: "なし", value: "" },
  { label: "電球", value: "fa-regular fa-lightbulb" },
  { label: "お知らせ", value: "fa-regular fa-bell" },
  { label: "カート", value: "fa-solid fa-cart-shopping" },
  { label: "吹き出し", value: "fa-regular fa-comment-dots" },
  { label: "星", value: "fa-regular fa-star" },
  { label: "はてなマーク", value: "fa-regular fa-question" },
  { label: "チェック", value: "fa-regular fa-circle-check" },
  { label: "ノート", value: "fa-solid fa-file-pen" },
  { label: "クリップボード", value: "fa-regular fa-clipboard" },
  { label: "鉛筆", value: "fa-solid fa-pen" },
  { label: "歯車", value: "fa-solid fa-gear" },
  { label: "注意", value: "fa-solid fa-triangle-exclamation" },
  { label: "いいね！", value: "fa-regular fa-thumbs-up" },
  { label: "低評価", value: "fa-regular fa-thumbs-down" },
  { label: "ハート", value: "fa-regular fa-heart" },
  { label: "旗", value: "fa-regular fa-flag" },
  { label: "ビックリマーク", value: "fa-solid fa-circle-exclamation" },
];
