export const ListAwesomeIcons = [
  { label: "なし", value: "" },
  { label: "番号", value: "numbers" },
  { label: "○番号", value: "disc-numbers" },
  { label: "ひし形番号", value: "dice-numbers" },
  { label: "大●", value: "large-disc" },
  { label: "ダブルアングル", value: "angle-double-right" },
  { label: "右アングル", value: "angle-right" },
  { label: "右矢印", value: "caret-right" },
  { label: "チェックマーク", value: "check" },
  { label: "ダブルチェック", value: "check-double" },
  { label: "サークルチェック", value: "circle-check" },
  { label: "サークルシェブロン", value: "circle-chevron-right" },
  { label: "サークルライト", value: "circle-right" },
  { label: "サークルXマーク", value: "circle-xmark" },
  { label: "クリップボードチェック", value: "clipboard-check" },
  { label: "大冠", value: "crown" },
  { label: "右差し指", value: "hand-point-right" },
  { label: "Point!", value: "hand-point-up" },
  { label: "ペンシル", value: "pencil" },
  { label: "ドクロマーク", value: "skull" },
  { label: "星マーク", value: "splotch" },
  { label: "スクエアチェックマーク", value: "square-check" },
  { label: "タグ", value: "tag" },
  { label: "警告", value: "triangle-exclamation" },
  { label: "犬の手", value: "dog-hand" },
];
